pipeline {
  agent {
    docker {
      image 'node:16-alpine'
    }
  }

  stages {

    stage('Check Node Version') {
      steps {
        sh 'node --version'
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('node-jenkins-demo') {
          sh 'npm install'
        }
      }
    }

    stage('Run App') {
      steps {
        dir('node-jenkins-demo') {
          sh 'node app.js'
        }
      }
    }
  }
}
